/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sda.ghidra.datatype;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-01-06")
public enum DataTypeSimple implements org.apache.thrift.TEnum {
  Void(1),
  Bool(2),
  Byte(3),
  Int8(4),
  Int16(5),
  Int32(6),
  Int64(7),
  UInt16(8),
  UInt32(9),
  UInt64(10),
  Float(11),
  Double(12);

  private final int value;

  private DataTypeSimple(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static DataTypeSimple findByValue(int value) { 
    switch (value) {
      case 1:
        return Void;
      case 2:
        return Bool;
      case 3:
        return Byte;
      case 4:
        return Int8;
      case 5:
        return Int16;
      case 6:
        return Int32;
      case 7:
        return Int64;
      case 8:
        return UInt16;
      case 9:
        return UInt32;
      case 10:
        return UInt64;
      case 11:
        return Float;
      case 12:
        return Double;
      default:
        return null;
    }
  }
}
