#include "NativeGroup_WATER.h"



//Native init
#define NATIVE(name) GAME_NATIVE_INIT(WATER, ##name)

using namespace SE;

//Natives
NATIVE(GET_WATER_HEIGHT)
NATIVE(GET_WATER_HEIGHT_NO_WAVES)
NATIVE(TEST_PROBE_AGAINST_WATER)
NATIVE(TEST_PROBE_AGAINST_ALL_WATER)
NATIVE(TEST_VERTICAL_PROBE_AGAINST_ALL_WATER)
NATIVE(MODIFY_WATER)
NATIVE(_ADD_CURRENT_RISE)
NATIVE(_REMOVE_CURRENT_RISE)
NATIVE(_SET_CURRENT_INTENSITY)
NATIVE(_GET_CURRENT_INTENSITY)
NATIVE(_RESET_CURRENT_INTENSITY)


//Native list
STATIC_FIELD_INIT(IGameNativeGroup<WATER>::m_natives)
{
	&WATER::GET_WATER_HEIGHT,
	&WATER::GET_WATER_HEIGHT_NO_WAVES,
	&WATER::TEST_PROBE_AGAINST_WATER,
	&WATER::TEST_PROBE_AGAINST_ALL_WATER,
	&WATER::TEST_VERTICAL_PROBE_AGAINST_ALL_WATER,
	&WATER::MODIFY_WATER,
	&WATER::_ADD_CURRENT_RISE,
	&WATER::_REMOVE_CURRENT_RISE,
	&WATER::_SET_CURRENT_INTENSITY,
	&WATER::_GET_CURRENT_INTENSITY,
	&WATER::_RESET_CURRENT_INTENSITY,
};