#include "NativeGroup_TIME.h"



//Native init
#define NATIVE(name) GAME_NATIVE_INIT(TIME, ##name)

using namespace SE;

//Natives
NATIVE(SET_CLOCK_TIME)
NATIVE(PAUSE_CLOCK)
NATIVE(ADVANCE_CLOCK_TIME_TO)
NATIVE(ADD_TO_CLOCK_TIME)
NATIVE(GET_CLOCK_HOURS)
NATIVE(GET_CLOCK_MINUTES)
NATIVE(GET_CLOCK_SECONDS)
NATIVE(SET_CLOCK_DATE)
NATIVE(GET_CLOCK_DAY_OF_WEEK)
NATIVE(GET_CLOCK_DAY_OF_MONTH)
NATIVE(GET_CLOCK_MONTH)
NATIVE(GET_CLOCK_YEAR)
NATIVE(GET_MILLISECONDS_PER_GAME_MINUTE)
NATIVE(GET_POSIX_TIME)
NATIVE(_GET_UTC_TIME)
NATIVE(GET_LOCAL_TIME)

//Native list
STATIC_FIELD_INIT(IGameNativeGroup<TIME>::m_natives)
{
	&TIME::SET_CLOCK_TIME,
	&TIME::PAUSE_CLOCK,
	&TIME::ADVANCE_CLOCK_TIME_TO,
	&TIME::ADD_TO_CLOCK_TIME,
	&TIME::GET_CLOCK_HOURS,
	&TIME::GET_CLOCK_MINUTES,
	&TIME::GET_CLOCK_SECONDS,
	&TIME::SET_CLOCK_DATE,
	&TIME::GET_CLOCK_DAY_OF_WEEK,
	&TIME::GET_CLOCK_DAY_OF_MONTH,
	&TIME::GET_CLOCK_MONTH,
	&TIME::GET_CLOCK_YEAR,
	&TIME::GET_MILLISECONDS_PER_GAME_MINUTE,
	&TIME::GET_POSIX_TIME,
	&TIME::_GET_UTC_TIME,
	&TIME::GET_LOCAL_TIME,
};