#include "NativeGroup_SYSTEM.h"



//Native init
#define NATIVE(name) GAME_NATIVE_INIT(SYSTEM, ##name)

using namespace SE;

//Natives
NATIVE(WAIT)
NATIVE(START_NEW_SCRIPT)
NATIVE(START_NEW_SCRIPT_WITH_ARGS)
NATIVE(START_NEW_SCRIPT_WITH_NAME_HASH)
NATIVE(START_NEW_SCRIPT_WITH_NAME_HASH_AND_ARGS)
NATIVE(TIMERA)
NATIVE(TIMERB)
NATIVE(SETTIMERA)
NATIVE(SETTIMERB)
NATIVE(TIMESTEP)
NATIVE(SIN)
NATIVE(COS)
NATIVE(SQRT)
NATIVE(POW)
NATIVE(VMAG)
NATIVE(VMAG2)
NATIVE(VDIST)
NATIVE(VDIST2)
NATIVE(SHIFT_LEFT)
NATIVE(SHIFT_RIGHT)
NATIVE(FLOOR)
NATIVE(CEIL)
NATIVE(ROUND)
NATIVE(TO_FLOAT)

//Native list
STATIC_FIELD_INIT(IGameNativeGroup<SYSTEM>::m_natives)
{
	&SYSTEM::WAIT,
	&SYSTEM::START_NEW_SCRIPT,
	&SYSTEM::START_NEW_SCRIPT_WITH_ARGS,
	&SYSTEM::START_NEW_SCRIPT_WITH_NAME_HASH,
	&SYSTEM::START_NEW_SCRIPT_WITH_NAME_HASH_AND_ARGS,
	&SYSTEM::TIMERA,
	&SYSTEM::TIMERB,
	&SYSTEM::SETTIMERA,
	&SYSTEM::SETTIMERB,
	&SYSTEM::TIMESTEP,
	&SYSTEM::SIN,
	&SYSTEM::COS,
	&SYSTEM::SQRT,
	&SYSTEM::POW,
	&SYSTEM::VMAG,
	&SYSTEM::VMAG2,
	&SYSTEM::VDIST,
	&SYSTEM::VDIST2,
	&SYSTEM::SHIFT_LEFT,
	&SYSTEM::SHIFT_RIGHT,
	&SYSTEM::FLOOR,
	&SYSTEM::CEIL,
	&SYSTEM::ROUND,
	&SYSTEM::TO_FLOAT,
};