#include "NativeGroup_WORLDPROBE.h"



//Native init
#define NATIVE(name) GAME_NATIVE_INIT(WORLDPROBE, ##name)

using namespace SE;

//Natives
NATIVE(START_SHAPE_TEST_LOS_PROBE)
NATIVE(_START_SHAPE_TEST_RAY)
NATIVE(START_SHAPE_TEST_BOUNDING_BOX)
NATIVE(START_SHAPE_TEST_BOX)
NATIVE(START_SHAPE_TEST_BOUND)
NATIVE(START_SHAPE_TEST_CAPSULE)
NATIVE(_START_SHAPE_TEST_CAPSULE_2)
NATIVE(_START_SHAPE_TEST_SURROUNDING_COORDS)
NATIVE(GET_SHAPE_TEST_RESULT)
NATIVE(_GET_SHAPE_TEST_RESULT_EX)
NATIVE(_SHAPE_TEST_RESULT_ENTITY)

//Native list
STATIC_FIELD_INIT(IGameNativeGroup<WORLDPROBE>::m_natives)
{
	&WORLDPROBE::START_SHAPE_TEST_LOS_PROBE,
	&WORLDPROBE::_START_SHAPE_TEST_RAY,
	&WORLDPROBE::START_SHAPE_TEST_BOUNDING_BOX,
	&WORLDPROBE::START_SHAPE_TEST_BOX,
	&WORLDPROBE::START_SHAPE_TEST_BOUND,
	&WORLDPROBE::START_SHAPE_TEST_CAPSULE,
	&WORLDPROBE::_START_SHAPE_TEST_CAPSULE_2,
	&WORLDPROBE::_START_SHAPE_TEST_SURROUNDING_COORDS,
	&WORLDPROBE::GET_SHAPE_TEST_RESULT,
	&WORLDPROBE::_GET_SHAPE_TEST_RESULT_EX,
	&WORLDPROBE::_SHAPE_TEST_RESULT_ENTITY,
};