#include "NativeGroup_ROPE.h"



//Native init
#define NATIVE(name) GAME_NATIVE_INIT(ROPE, ##name)

using namespace SE;

//Natives
NATIVE(ADD_ROPE)
NATIVE(DELETE_ROPE)
NATIVE(DELETE_CHILD_ROPE)
NATIVE(DOES_ROPE_EXIST)
NATIVE(ROPE_DRAW_SHADOW_ENABLED)
NATIVE(LOAD_ROPE_DATA)
NATIVE(PIN_ROPE_VERTEX)
NATIVE(UNPIN_ROPE_VERTEX)
NATIVE(GET_ROPE_VERTEX_COUNT)
NATIVE(ATTACH_ENTITIES_TO_ROPE)
NATIVE(ATTACH_ROPE_TO_ENTITY)
NATIVE(DETACH_ROPE_FROM_ENTITY)
NATIVE(ROPE_SET_UPDATE_PINVERTS)
NATIVE(_HIDE_ROPE)
NATIVE(_0x36CCB9BE67B970FD)
NATIVE(_0x84DE3B5FB3E666F0)
NATIVE(GET_ROPE_LAST_VERTEX_COORD)
NATIVE(GET_ROPE_VERTEX_COORD)
NATIVE(START_ROPE_WINDING)
NATIVE(STOP_ROPE_WINDING)
NATIVE(START_ROPE_UNWINDING_FRONT)
NATIVE(STOP_ROPE_UNWINDING_FRONT)
NATIVE(ROPE_CONVERT_TO_SIMPLE)
NATIVE(ROPE_LOAD_TEXTURES)
NATIVE(ROPE_ARE_TEXTURES_LOADED)
NATIVE(ROPE_UNLOAD_TEXTURES)
NATIVE(_0x271C9D3ACA5D6409)
NATIVE(_0xBC0CE682D4D05650)
NATIVE(_0xB1B6216CA2E7B55E)
NATIVE(_0xB743F735C03D7810)
NATIVE(_GET_ROPE_LENGTH)
NATIVE(ROPE_FORCE_LENGTH)
NATIVE(ROPE_RESET_LENGTH)
NATIVE(APPLY_IMPULSE_TO_CLOTH)
NATIVE(SET_DAMPING)
NATIVE(ACTIVATE_PHYSICS)
NATIVE(SET_CGOFFSET)
NATIVE(GET_CGOFFSET)
NATIVE(SET_CG_AT_BOUNDCENTER)
NATIVE(BREAK_ENTITY_GLASS)
NATIVE(SET_DISABLE_BREAKING)
NATIVE(_0xCC6E963682533882)
NATIVE(SET_DISABLE_FRAG_DAMAGE)

//Native list
STATIC_FIELD_INIT(IGameNativeGroup<ROPE>::m_natives)
{
	&ROPE::ADD_ROPE,
	&ROPE::DELETE_ROPE,
	&ROPE::DELETE_CHILD_ROPE,
	&ROPE::DOES_ROPE_EXIST,
	&ROPE::ROPE_DRAW_SHADOW_ENABLED,
	&ROPE::LOAD_ROPE_DATA,
	&ROPE::PIN_ROPE_VERTEX,
	&ROPE::UNPIN_ROPE_VERTEX,
	&ROPE::GET_ROPE_VERTEX_COUNT,
	&ROPE::ATTACH_ENTITIES_TO_ROPE,
	&ROPE::ATTACH_ROPE_TO_ENTITY,
	&ROPE::DETACH_ROPE_FROM_ENTITY,
	&ROPE::ROPE_SET_UPDATE_PINVERTS,
	&ROPE::_HIDE_ROPE,
	&ROPE::_0x36CCB9BE67B970FD,
	&ROPE::_0x84DE3B5FB3E666F0,
	&ROPE::GET_ROPE_LAST_VERTEX_COORD,
	&ROPE::GET_ROPE_VERTEX_COORD,
	&ROPE::START_ROPE_WINDING,
	&ROPE::STOP_ROPE_WINDING,
	&ROPE::START_ROPE_UNWINDING_FRONT,
	&ROPE::STOP_ROPE_UNWINDING_FRONT,
	&ROPE::ROPE_CONVERT_TO_SIMPLE,
	&ROPE::ROPE_LOAD_TEXTURES,
	&ROPE::ROPE_ARE_TEXTURES_LOADED,
	&ROPE::ROPE_UNLOAD_TEXTURES,
	&ROPE::_0x271C9D3ACA5D6409,
	&ROPE::_0xBC0CE682D4D05650,
	&ROPE::_0xB1B6216CA2E7B55E,
	&ROPE::_0xB743F735C03D7810,
	&ROPE::_GET_ROPE_LENGTH,
	&ROPE::ROPE_FORCE_LENGTH,
	&ROPE::ROPE_RESET_LENGTH,
	&ROPE::APPLY_IMPULSE_TO_CLOTH,
	&ROPE::SET_DAMPING,
	&ROPE::ACTIVATE_PHYSICS,
	&ROPE::SET_CGOFFSET,
	&ROPE::GET_CGOFFSET,
	&ROPE::SET_CG_AT_BOUNDCENTER,
	&ROPE::BREAK_ENTITY_GLASS,
	&ROPE::SET_DISABLE_BREAKING,
	&ROPE::_0xCC6E963682533882,
	&ROPE::SET_DISABLE_FRAG_DAMAGE,
};