#include "NativeGroup_FIRE.h"



//Native init
#define NATIVE(name) GAME_NATIVE_INIT(FIRE, ##name)

using namespace SE;

//Natives
NATIVE(START_SCRIPT_FIRE)
NATIVE(REMOVE_SCRIPT_FIRE)
NATIVE(START_ENTITY_FIRE)
NATIVE(STOP_ENTITY_FIRE)
NATIVE(IS_ENTITY_ON_FIRE)
NATIVE(GET_NUMBER_OF_FIRES_IN_RANGE)
NATIVE(STOP_FIRE_IN_RANGE)
NATIVE(GET_CLOSEST_FIRE_POS)
NATIVE(ADD_EXPLOSION)
NATIVE(ADD_OWNED_EXPLOSION)
NATIVE(ADD_EXPLOSION_WITH_USER_VFX)
NATIVE(IS_EXPLOSION_IN_AREA)
NATIVE(_0x6070104B699B2EF4)
NATIVE(IS_EXPLOSION_IN_SPHERE)
NATIVE(IS_EXPLOSION_IN_ANGLED_AREA)
NATIVE(_GET_PED_INSIDE_EXPLOSION_AREA)

//Native list
STATIC_FIELD_INIT(IGameNativeGroup<FIRE>::m_natives)
{
	&FIRE::START_SCRIPT_FIRE,
	&FIRE::REMOVE_SCRIPT_FIRE,
	&FIRE::START_ENTITY_FIRE,
	&FIRE::STOP_ENTITY_FIRE,
	&FIRE::IS_ENTITY_ON_FIRE,
	&FIRE::GET_NUMBER_OF_FIRES_IN_RANGE,
	&FIRE::STOP_FIRE_IN_RANGE,
	&FIRE::GET_CLOSEST_FIRE_POS,
	&FIRE::ADD_EXPLOSION,
	&FIRE::ADD_OWNED_EXPLOSION,
	&FIRE::ADD_EXPLOSION_WITH_USER_VFX,
	&FIRE::IS_EXPLOSION_IN_AREA,
	&FIRE::_0x6070104B699B2EF4,
	&FIRE::IS_EXPLOSION_IN_SPHERE,
	&FIRE::IS_EXPLOSION_IN_ANGLED_AREA,
	&FIRE::_GET_PED_INSIDE_EXPLOSION_AREA,
};