/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "datatype_constants.h"

namespace ghidra { namespace datatype {

const datatypeConstants g_datatype_constants;

datatypeConstants::datatypeConstants() {
}

}} // namespace

