/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef datatype_CONSTANTS_H
#define datatype_CONSTANTS_H

#include "datatype_types.h"

namespace ghidra { namespace datatype {

class datatypeConstants {
 public:
  datatypeConstants();

};

extern const datatypeConstants g_datatype_constants;

}} // namespace

#endif
