/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "function_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace ghidra { namespace function {


SFunctionRange::~SFunctionRange() throw() {
}


void SFunctionRange::__set_minOffset(const int32_t val) {
  this->minOffset = val;
}

void SFunctionRange::__set_maxOffset(const int32_t val) {
  this->maxOffset = val;
}
std::ostream& operator<<(std::ostream& out, const SFunctionRange& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SFunctionRange::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->minOffset);
          this->__isset.minOffset = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->maxOffset);
          this->__isset.maxOffset = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SFunctionRange::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SFunctionRange");

  xfer += oprot->writeFieldBegin("minOffset", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->minOffset);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("maxOffset", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->maxOffset);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SFunctionRange &a, SFunctionRange &b) {
  using ::std::swap;
  swap(a.minOffset, b.minOffset);
  swap(a.maxOffset, b.maxOffset);
  swap(a.__isset, b.__isset);
}

SFunctionRange::SFunctionRange(const SFunctionRange& other0) {
  minOffset = other0.minOffset;
  maxOffset = other0.maxOffset;
  __isset = other0.__isset;
}
SFunctionRange& SFunctionRange::operator=(const SFunctionRange& other1) {
  minOffset = other1.minOffset;
  maxOffset = other1.maxOffset;
  __isset = other1.__isset;
  return *this;
}
void SFunctionRange::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SFunctionRange(";
  out << "minOffset=" << to_string(minOffset);
  out << ", " << "maxOffset=" << to_string(maxOffset);
  out << ")";
}


SFunctionSignature::~SFunctionSignature() throw() {
}


void SFunctionSignature::__set_returnType(const  ::ghidra::shared::STypeUnit& val) {
  this->returnType = val;
}

void SFunctionSignature::__set_arguments(const std::vector< ::ghidra::shared::STypeUnit> & val) {
  this->arguments = val;
}
std::ostream& operator<<(std::ostream& out, const SFunctionSignature& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SFunctionSignature::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->returnType.read(iprot);
          this->__isset.returnType = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->arguments.clear();
            uint32_t _size2;
            ::apache::thrift::protocol::TType _etype5;
            xfer += iprot->readListBegin(_etype5, _size2);
            this->arguments.resize(_size2);
            uint32_t _i6;
            for (_i6 = 0; _i6 < _size2; ++_i6)
            {
              xfer += this->arguments[_i6].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.arguments = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SFunctionSignature::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SFunctionSignature");

  xfer += oprot->writeFieldBegin("returnType", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->returnType.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("arguments", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->arguments.size()));
    std::vector< ::ghidra::shared::STypeUnit> ::const_iterator _iter7;
    for (_iter7 = this->arguments.begin(); _iter7 != this->arguments.end(); ++_iter7)
    {
      xfer += (*_iter7).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SFunctionSignature &a, SFunctionSignature &b) {
  using ::std::swap;
  swap(a.returnType, b.returnType);
  swap(a.arguments, b.arguments);
  swap(a.__isset, b.__isset);
}

SFunctionSignature::SFunctionSignature(const SFunctionSignature& other8) {
  returnType = other8.returnType;
  arguments = other8.arguments;
  __isset = other8.__isset;
}
SFunctionSignature& SFunctionSignature::operator=(const SFunctionSignature& other9) {
  returnType = other9.returnType;
  arguments = other9.arguments;
  __isset = other9.__isset;
  return *this;
}
void SFunctionSignature::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SFunctionSignature(";
  out << "returnType=" << to_string(returnType);
  out << ", " << "arguments=" << to_string(arguments);
  out << ")";
}


SFunction::~SFunction() throw() {
}


void SFunction::__set_id(const Id val) {
  this->id = val;
}

void SFunction::__set_name(const std::string& val) {
  this->name = val;
}

void SFunction::__set_comment(const std::string& val) {
  this->comment = val;
}

void SFunction::__set_argumentNames(const std::vector<std::string> & val) {
  this->argumentNames = val;
}

void SFunction::__set_signature(const SFunctionSignature& val) {
  this->signature = val;
}

void SFunction::__set_ranges(const std::vector<SFunctionRange> & val) {
  this->ranges = val;
}
std::ostream& operator<<(std::ostream& out, const SFunction& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SFunction::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->id);
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->comment);
          this->__isset.comment = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->argumentNames.clear();
            uint32_t _size10;
            ::apache::thrift::protocol::TType _etype13;
            xfer += iprot->readListBegin(_etype13, _size10);
            this->argumentNames.resize(_size10);
            uint32_t _i14;
            for (_i14 = 0; _i14 < _size10; ++_i14)
            {
              xfer += iprot->readString(this->argumentNames[_i14]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.argumentNames = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->signature.read(iprot);
          this->__isset.signature = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->ranges.clear();
            uint32_t _size15;
            ::apache::thrift::protocol::TType _etype18;
            xfer += iprot->readListBegin(_etype18, _size15);
            this->ranges.resize(_size15);
            uint32_t _i19;
            for (_i19 = 0; _i19 < _size15; ++_i19)
            {
              xfer += this->ranges[_i19].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.ranges = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SFunction::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SFunction");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I64, 1);
  xfer += oprot->writeI64(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("comment", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->comment);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("argumentNames", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->argumentNames.size()));
    std::vector<std::string> ::const_iterator _iter20;
    for (_iter20 = this->argumentNames.begin(); _iter20 != this->argumentNames.end(); ++_iter20)
    {
      xfer += oprot->writeString((*_iter20));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("signature", ::apache::thrift::protocol::T_STRUCT, 5);
  xfer += this->signature.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("ranges", ::apache::thrift::protocol::T_LIST, 6);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->ranges.size()));
    std::vector<SFunctionRange> ::const_iterator _iter21;
    for (_iter21 = this->ranges.begin(); _iter21 != this->ranges.end(); ++_iter21)
    {
      xfer += (*_iter21).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SFunction &a, SFunction &b) {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.name, b.name);
  swap(a.comment, b.comment);
  swap(a.argumentNames, b.argumentNames);
  swap(a.signature, b.signature);
  swap(a.ranges, b.ranges);
  swap(a.__isset, b.__isset);
}

SFunction::SFunction(const SFunction& other22) {
  id = other22.id;
  name = other22.name;
  comment = other22.comment;
  argumentNames = other22.argumentNames;
  signature = other22.signature;
  ranges = other22.ranges;
  __isset = other22.__isset;
}
SFunction& SFunction::operator=(const SFunction& other23) {
  id = other23.id;
  name = other23.name;
  comment = other23.comment;
  argumentNames = other23.argumentNames;
  signature = other23.signature;
  ranges = other23.ranges;
  __isset = other23.__isset;
  return *this;
}
void SFunction::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SFunction(";
  out << "id=" << to_string(id);
  out << ", " << "name=" << to_string(name);
  out << ", " << "comment=" << to_string(comment);
  out << ", " << "argumentNames=" << to_string(argumentNames);
  out << ", " << "signature=" << to_string(signature);
  out << ", " << "ranges=" << to_string(ranges);
  out << ")";
}

}} // namespace
