/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ghidra_constants.h"

namespace ghidra { namespace packet {

const ghidraConstants g_ghidra_constants;

ghidraConstants::ghidraConstants() {
}

}} // namespace

