/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ghidra_CONSTANTS_H
#define ghidra_CONSTANTS_H

#include "ghidra_types.h"



class ghidraConstants {
 public:
  ghidraConstants();

};

extern const ghidraConstants g_ghidra_constants;



#endif
